version: '3.8'


services:
 app:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "19000:19000"
     - "19001:19001"
     - "19002:19002"
   volumes:
     - .:/usr/src/app
